name: E2E Tests - Cypress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repositório
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências do frontend
        working-directory: ./frontend
        run: npm install

      - name: 🚀 Rodar testes E2E com Cypress
        working-directory: ./frontend
        run: npx cypress run
